#!/bin/sh

# variables

user=$(stat -f %Su /dev/console)
userHome=$(/usr/bin/dscl . -read "/Users/$user" NFSHomeDirectory | /usr/bin/awk ' { print $NF } ')


# kill the installer

/usr/bin/pkill "Installer"


# silent install

echo "Beginning installation of AutoCAD LT 2023..."
/private/tmp/Install\ Autodesk\ AutoCAD\ LT\ 2023\ for\ Mac.app/Contents/Helper/Setup.app/Contents/MacOS/Setup --silent ; 


# let installer complete

sleep 30


# add to current user's dock
#   second variable to check for homedir location on non-boot volume

echo "Adding to current user's dock..."
/usr/local/bin/dockutil --add /Applications/Autodesk/AutoCAD\ LT\ 2023/AutoCAD\ LT\ 2023.app --replacing 'AutoCAD LT 2023' "$userHome"


# cleanup

echo "Removing installer..."
rm -rf /private/tmp/Install\ Autodesk\ AutoCAD\ LT\ 2023\ for\ Mac.app

exit 0
