#!/bin/bash

# this is the two-step, two script version:
#  first script (before) checks app status, closes app and writes a variable
#  second script (after) reads variable to decide whether to reopen app

# Read in the application name from the temp file
APP_NAME="$(cat /private/var/tmp/itwasrunning)"

# Reopen the app if it was running before
if pgrep -x "$APP_NAME" > /dev/null; then
    echo "$APP_NAME is running again. No need to reopen."
else
    echo "$APP_NAME was not running before, reopening it now."
    osascript -e "tell application \"$APP_NAME\" to activate"
fi

# Remove the temp file
if [ -e /private/var/tmp/itwasrunning ]; then
  rm /private/var/tmp/itwasrunning
fi

exit
